version: '3'
services:
  postgres:
    image: postgres:14.2-alpine
    container_name: pg-ms-email
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ms-email
    ports:
      - 5432:5432
    volumes:
      - $HOME/.docker-postgres/:/var/lib/postgresql
      - $HOME/.docker-postgres/data/:/var/lib/postgresql/data
    networks:
      - postgres-network

  pgadmin4:
    image: dpage/pgadmin4
    container_name: pgadmin4-ms-email
    environment:
      PGADMIN_DEFAULT_EMAIL: "pgadmin4@email.com"
      PGADMIN_DEFAULT_PASSWORD: "pgadmin4"
    ports:
      - 15432:80
    depends_on:
      - postgres
    networks:
      - postgres-network

networks: 
  postgres-network:
    driver: bridge
